/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NuevaMisionRouteImport } from './routes/nueva-mision'
import { Route as PersonajeRouteImport } from './routes/personaje'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaMisionRoute = NuevaMisionRouteImport.update({
  id: '/nueva-mision',
  path: '/nueva-mision',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonajeRoute = PersonajeRouteImport.update({
  id: '/personaje',
  path: '/personaje',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nueva-mision': typeof NuevaMisionRoute
  '/personaje': typeof PersonajeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nueva-mision': typeof NuevaMisionRoute
  '/personaje': typeof PersonajeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nueva-mision': typeof NuevaMisionRoute
  '/personaje': typeof PersonajeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nueva-mision' | '/personaje'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nueva-mision' | '/personaje'
  id: '__root__' | '/' | '/nueva-mision' | '/personaje'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NuevaMisionRoute: typeof NuevaMisionRoute
  PersonajeRoute: typeof PersonajeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-mision': {
      id: '/nueva-mision'
      path: '/nueva-mision'
      fullPath: '/nueva-mision'
      preLoaderRoute: typeof NuevaMisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personaje': {
      id: '/personaje'
      path: '/personaje'
      fullPath: '/personaje'
      preLoaderRoute: typeof PersonajeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NuevaMisionRoute: NuevaMisionRoute,
  PersonajeRoute: PersonajeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
